// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {

  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKPzQeDRwxrIB9bxpQzD8BOOdF9_d3AbM',
    appId: '1:753685502385:web:ac72ce80b5282d013c8590',
    messagingSenderId: '753685502385',
    projectId: 'mena-359010',
    authDomain: 'mena-359010.firebaseapp.com',
    databaseURL: 'https://mena-359010-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mena-359010.appspot.com',
    measurementId: 'G-3HJZ5Q2G3B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB9iEhhL0v2gsL2yVnlbZ_V0TRITpCX23o',
    appId: '1:753685502385:android:336d80b5ee6591c93c8590',
    messagingSenderId: '753685502385',
    projectId: 'mena-359010',
    databaseURL: 'https://mena-359010-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mena-359010.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDnEbas_Tz-WBJA8_2iTyCymPsAdU9_Ikk',
    appId: '1:753685502385:ios:428d0694dce7139d3c8590',
    messagingSenderId: '753685502385',
    projectId: 'mena-359010',
    databaseURL: 'https://mena-359010-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mena-359010.appspot.com',
    iosClientId: '753685502385-iu00f40brog6ij1r398l9e68tkc3ksob.apps.googleusercontent.com',
    iosBundleId: 'com.brainclick.mena',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDnEbas_Tz-WBJA8_2iTyCymPsAdU9_Ikk',
    appId: '1:753685502385:ios:428d0694dce7139d3c8590',
    messagingSenderId: '753685502385',
    projectId: 'mena-359010',
    databaseURL: 'https://mena-359010-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mena-359010.appspot.com',
    iosClientId: '753685502385-iu00f40brog6ij1r398l9e68tkc3ksob.apps.googleusercontent.com',
    iosBundleId: 'com.brainclick.mena',
  );

}