import 'package:flutter/material.dart';



class ProviderDepartmentsBody extends StatelessWidget {
  const ProviderDepartmentsBody({
    Key? key,
  }) : super(key: key);

  @override
  Widget build(BuildContext context) {
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: const[
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
         Text('Departments jkdgfhnm,dsfnbnm ndhjn kjsahcndaklscjkas dclkl '),
      ],
    );
  }
}